### ISSUE TITLE
add favicon to demo.bokeh.org

### ISSUE THREAD

**Issue by timsnyder** [bokeh/demo.bokeh.org#14]
I noticed that the favicon stuff isn't setup on demo.bokeh.org.  Not the biggest deal but you should probably swipe the icon from bokeh.org so that it isn't unset.

**Comment by bryevdv** [comment]
It's going to take a little bit more, the page at `demo.bokeh.org` is actually served directly from the Bokeh server (as are all the app pages) so we will need to add favicon support to the Bokeh server itself. I've actually thought about this in the last couple of weeks but had not made an issue for it on the main repo yet. It you want to make one linked to this that would be helpful

**Comment by bryevdv** [comment]
closing this issue here as there in a relevant issue in the main repo
