### ISSUE TITLE
Links Broken for Source code on multiple plot

### ISSUE THREAD

**Issue by ClimateYukon** [bokeh/demo.bokeh.org#8]
There are a couple of broken links on https://demo.bokehplots.com/

Weather source code link : 
https://github.com/bokeh/bokeh-demos/tree/master/weather
instead of 
https://github.com/bokeh/bokeh/tree/master/examples/app/weather

Stocks source code link : 
https://github.com/bokeh/bokeh/blob/master/examples/app/stocks.py
instead of 
https://github.com/bokeh/bokeh/blob/master/examples/app/stocks

**Comment by bryevdv** [comment]
Thanks, the stocks one was already fixed in `master` and I just updated the weather one. The site should be re-deployed in a few days.
